// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB87stToF1pVNfxCNwJmUVqvd9WzM40wEM',
    appId: '1:229332106763:web:1ee0f22d3627e7db0d110e',
    messagingSenderId: '229332106763',
    projectId: 'taskflow-66b0e',
    authDomain: 'taskflow-66b0e.firebaseapp.com',
    storageBucket: 'taskflow-66b0e.firebasestorage.app',
    measurementId: 'G-8XBF1FB1ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRoOOPTln5H_xolZ2LDyKY4uZAFt1Zys',
    appId: '1:229332106763:android:2da30b70c4bce6990d110e',
    messagingSenderId: '229332106763',
    projectId: 'taskflow-66b0e',
    storageBucket: 'taskflow-66b0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5E2jRbVx0rcKerOpENlJinyIE6-bbS4Q',
    appId: '1:229332106763:ios:e4d52a76f78bec320d110e',
    messagingSenderId: '229332106763',
    projectId: 'taskflow-66b0e',
    storageBucket: 'taskflow-66b0e.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5E2jRbVx0rcKerOpENlJinyIE6-bbS4Q',
    appId: '1:229332106763:ios:e4d52a76f78bec320d110e',
    messagingSenderId: '229332106763',
    projectId: 'taskflow-66b0e',
    storageBucket: 'taskflow-66b0e.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB87stToF1pVNfxCNwJmUVqvd9WzM40wEM',
    appId: '1:229332106763:web:8adcee14ba7feab30d110e',
    messagingSenderId: '229332106763',
    projectId: 'taskflow-66b0e',
    authDomain: 'taskflow-66b0e.firebaseapp.com',
    storageBucket: 'taskflow-66b0e.firebasestorage.app',
    measurementId: 'G-49NBVQD57T',
  );
}
